// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Admin
    {
        public short IdAdmin { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
    }
}