// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Alumnos
    {
        public short IdAlumno { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string MailAlumno { get; set; }
        public string Domicilio { get; set; }
        public string Barrio { get; set; }
        public string Celular { get; set; }
        public string FechaDeNacimiento { get; set; }
        public string Dni { get; set; }
        public short Edad { get; set; }
        public string ObraSocial { get; set; }
        public string GrupoSanguineo { get; set; }
        public string ObservacionesFisicas { get; set; }
        public string NombreDeMadre { get; set; }
        public string DireccionMadre { get; set; }
        public string CelularMadre { get; set; }
        public string MailMadre { get; set; }
        public string NombreDePadre { get; set; }
        public string DireccionPadre { get; set; }
        public string CelularPadre { get; set; }
        public string MailPadre { get; set; }
        public string EnCasoDeEmergenciaA { get; set; }
        public string Telefono { get; set; }
        public string CelularEmergencia { get; set; }
        public string Parentesco { get; set; }
        public string DisciplinaQueCursa { get; set; }
        public string AnioDeComienzo { get; set; }
    }
}