// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Model.Models
{
    public partial class EstudioDeDanzasContext : DbContext
    {
        public EstudioDeDanzasContext()
        {
        }

        public EstudioDeDanzasContext(DbContextOptions<EstudioDeDanzasContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<Butacas> Butacas { get; set; }
        public virtual DbSet<Funcion> Funcion { get; set; }
        public virtual DbSet<Platea> Platea { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<Tokens> Tokens { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Admin>(entity =>
            {
                entity.HasKey(e => e.IdAdmin);

                entity.Property(e => e.IdAdmin).ValueGeneratedNever();

                entity.Property(e => e.Contrasena)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsFixedLength();

                entity.Property(e => e.Usuario)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();
            });

            modelBuilder.Entity<Alumnos>(entity =>
            {
                entity.HasKey(e => e.IdAlumno);

                entity.Property(e => e.AnioDeComienzo)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.Barrio)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.Celular)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.CelularEmergencia)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.CelularMadre)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.CelularPadre)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.DireccionMadre)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.DireccionPadre)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.DisciplinaQueCursa)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.Dni)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsFixedLength();

                entity.Property(e => e.Domicilio)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.EnCasoDeEmergenciaA)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.FechaDeNacimiento)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsFixedLength();

                entity.Property(e => e.GrupoSanguineo)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.MailAlumno)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsFixedLength();

                entity.Property(e => e.MailMadre)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.MailPadre)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.NombreDeMadre)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.NombreDePadre)
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.ObraSocial)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.ObservacionesFisicas)
                    .HasMaxLength(255)
                    .IsFixedLength();

                entity.Property(e => e.Parentesco)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsFixedLength();

                entity.Property(e => e.Telefono)
                    .HasMaxLength(50)
                    .IsFixedLength();
            });

            modelBuilder.Entity<Butacas>(entity =>
            {
                entity.HasKey(e => e.IdButaca);

                entity.Property(e => e.IdButaca).HasColumnName("Id_Butaca");

                entity.Property(e => e.IdFuncion).HasColumnName("Id_Funcion");

                entity.Property(e => e.IdPlatea).HasColumnName("Id_Platea");

                entity.Property(e => e.NroButaca).HasColumnName("Nro_Butaca");

                entity.HasOne(d => d.IdFuncionNavigation)
                    .WithMany(p => p.Butacas)
                    .HasForeignKey(d => d.IdFuncion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Butacas_Funcion");

                entity.HasOne(d => d.IdPlateaNavigation)
                    .WithMany(p => p.Butacas)
                    .HasForeignKey(d => d.IdPlatea)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Butacas_Platea");
            });

            modelBuilder.Entity<Funcion>(entity =>
            {
                entity.HasKey(e => e.IdFuncion);

                entity.Property(e => e.IdFuncion)
                    .ValueGeneratedNever()
                    .HasColumnName("Id_Funcion");

                entity.Property(e => e.TipoFuncion)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnName("Tipo_Funcion");
            });

            modelBuilder.Entity<Platea>(entity =>
            {
                entity.HasKey(e => e.IdPlatea);

                entity.Property(e => e.IdPlatea)
                    .ValueGeneratedNever()
                    .HasColumnName("Id_Platea");

                entity.Property(e => e.IdFuncion).HasColumnName("Id_Funcion");

                entity.Property(e => e.TipoPlatea)
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnName("Tipo_Platea")
                    .IsFixedLength();

                entity.HasOne(d => d.IdFuncionNavigation)
                    .WithMany(p => p.Platea)
                    .HasForeignKey(d => d.IdFuncion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Platea_Funcion");
            });

            modelBuilder.Entity<Reservas>(entity =>
            {
                entity.HasKey(e => e.IdReserva);

                entity.Property(e => e.IdReserva).HasColumnName("Id_Reserva");

                entity.Property(e => e.IdButaca).HasColumnName("Id_Butaca");

                entity.Property(e => e.IdFuncion).HasColumnName("Id_Funcion");

                entity.Property(e => e.TokenCreated)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsFixedLength();

                entity.HasOne(d => d.IdButacaNavigation)
                    .WithMany(p => p.Reservas)
                    .HasForeignKey(d => d.IdButaca)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Reservas_Butacas");

                entity.HasOne(d => d.IdFuncionNavigation)
                    .WithMany(p => p.Reservas)
                    .HasForeignKey(d => d.IdFuncion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Reservas_Funcion");

                entity.HasOne(d => d.TokenCreatedNavigation)
                    .WithMany(p => p.Reservas)
                    .HasForeignKey(d => d.TokenCreated)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Reservas_Tokens");
            });

            modelBuilder.Entity<Tokens>(entity =>
            {
                entity.HasKey(e => e.TokenCreated);

                entity.Property(e => e.TokenCreated)
                    .HasMaxLength(255)
                    .IsFixedLength();

                entity.Property(e => e.CreateDate).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}