// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Funcion
    {
        public Funcion()
        {
            Butacas = new HashSet<Butacas>();
            Platea = new HashSet<Platea>();
            Reservas = new HashSet<Reservas>();
        }

        public short IdFuncion { get; set; }
        public string TipoFuncion { get; set; }

        public virtual ICollection<Butacas> Butacas { get; set; }
        public virtual ICollection<Platea> Platea { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}