// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Platea
    {
        public Platea()
        {
            Butacas = new HashSet<Butacas>();
        }

        public short IdPlatea { get; set; }
        public string TipoPlatea { get; set; }
        public short IdFuncion { get; set; }

        public virtual Funcion IdFuncionNavigation { get; set; }
        public virtual ICollection<Butacas> Butacas { get; set; }
    }
}