// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models
{
    public partial class Tokens
    {
        public Tokens()
        {
            Reservas = new HashSet<Reservas>();
        }

        public string TokenCreated { get; set; }
        public short AssignedTickets { get; set; }
        public short UsedTickets { get; set; }
        public bool ValidToken { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}